### ISSUE TITLE
Change branch protection to rulesets

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/admin#15]
### Short Description

GitHub has [introduced rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets), would be good to change the current setup to those going forwards

**Comment by drmatthews** [comment]
Looks like the change to rulesets has been done.

**Comment by paddyroddy** [comment]
> Looks like the change to rulesets has been done.

It has https://github.com/UCL-MIRSG/admin/pull/22, but not sure if it's working
